### ISSUE TITLE
pullIntervalSeconds: docker fails to run with exit code 1

### ISSUE THREAD

**Issue by ephemeraldrive** [logzio/microsoft-graph#125]
When pullIntervalSeconds is commented out, the Docker container starts fine (musing_kare below). When pullIntervalSeconds is present on config.yaml, the Docker container throws an exception ant terminates (kind_payne). 

```
$ docker container ls -a
CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS                         PORTS               NAMES
97a194bba2ea        logzio/logzio-msgraph   "/bin/sh -c 'java -j…"   7 seconds ago       Up 6 seconds                                       musing_kare
221709ca795f        logzio/logzio-msgraph   "/bin/sh -c 'java -j…"   About an hour ago   Exited (1) About an hour ago                       kind_payne

$ docker container logs 221709ca795f
Exception in thread "main" Cannot create property=azureADClient for JavaBean=objects.MSGraphConfiguration@5680a178
 in 'reader', line 1, column 1:
    senderParams:
    ^
Cannot create property=pullIntervalSeconds for JavaBean=objects.AzureADClient@244038d0
 in 'reader', line 5, column 3:
      pullIntervalSeconds: 300
      ^
Unable to find property 'pullIntervalSeconds' on class: objects.AzureADClient
 in 'reader', line 5, column 24:
      pullIntervalSeconds: 300
                           ^

 in 'reader', line 5, column 3:
      pullIntervalSeconds: 300
      ^

	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:268)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:149)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:309)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:215)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:205)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:164)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:148)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:525)
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:453)
	at main.MSClient.loadMSGraphConfig(MSClient.java:59)
	at main.MSClient.<init>(MSClient.java:28)
	at main.Main.main(Main.java:16)
Caused by: Cannot create property=pullIntervalSeconds for JavaBean=objects.AzureADClient@244038d0
 in 'reader', line 5, column 3:
      pullIntervalSeconds: 300
      ^
Unable to find property 'pullIntervalSeconds' on class: objects.AzureADClient
 in 'reader', line 5, column 24:
      pullIntervalSeconds: 300
                           ^

	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:268)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:149)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:215)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:205)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.newInstance(Constructor.java:283)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:245)
	... 11 more
Caused by: org.yaml.snakeyaml.error.YAMLException: Unable to find property 'pullIntervalSeconds' on class: objects.AzureADClient
	at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:158)
	at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:148)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.getProperty(Constructor.java:287)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:208)
	... 16 more
```

**Comment by yyyogev** [comment]
@ephemeraldrive thank you for the update!
It's fixed now. Remove and re-pull the docker.
